function createcostfigure(Y1)
%CREATEFIGURE1(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 31-Jul-2018 12:24:57

% Create figure
figure1 = figure('DefaultAxesFontSize',16);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0749808722264728 0.106844741235392 0.885233358837031 0.818155258764608]);
hold(axes1,'on');

% Create plot
plot(Y1,'Marker','.','LineStyle','none');

% Create ylabel
ylabel('Cost)');

% Create xlabel
xlabel('Iteration');

% Create title
title('Cost');

box(axes1,'on');
