function createlqtexamplemulitplotfigure(X1, YMatrix1)
%CREATEFIGURE1(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 31-Jul-2018 13:17:21

% Create figure
figure1 = figure('DefaultAxesFontSize',16);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0573833205814843 0.11 0.90283091048202 0.815]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',3,'Parent',axes1);
set(plot1(1),'DisplayName','Q=1','LineStyle','-.');
set(plot1(2),'DisplayName','Q=10','LineStyle',':');
set(plot1(3),'DisplayName','Q=25','LineStyle','--');

% Create ylabel
ylabel('x(t)');

% Create xlabel
xlabel('Time (s)');

% Create title
title('Optimal State Trajectories');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 10]);
% Set the remaining axes properties
set(axes1,'XGrid','on','XTick',[0 2.5 5 7.5 10 12.5 15],'YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','southeast','FontSize',16);

